### ISSUE TITLE
Proposition de post : Docker

### ISSUE THREAD

**Issue by Uhsac** [putaindecode/putaindecode.fr#430]
Salut à vous,

Je suis votre site depuis un moment et je me suis dis que je pourrais aider un peu avec mes quelques connaissance.

Je suis un grand fan de Docker et je l'utilise pour un peu tout depuis un peu moins d'un an. J'aimerais donc savoir si ça pourrait intéresser que je rédige un petit article sur comment utiliser docker et ses copains (docker-compose et docker-machine) pour créer des environnement de dev et prod et deployer rapidement son code.

Je me dis que cet article pourrait s'inscrire dans la lignée de l'articles sur le déploiement continu.

Voila voila j'attend vos retour.

**Comment by MoOx** [comment]
:+1:

Je n'ai pas idée du volume d'infos à partager mais si ça doit faire un gros pavé, faudrait pas hésiter à découper. A toi de nous dire ;)

**Comment by drazik** [comment]
Carrément !

**Comment by magsout** [comment]
Ca  m'intéresse à fond surtout que j'aimerai l'utiliser mais jamais pris le temps de regarder la donc. Je suis pour.  Comme l'a dit @MoOx surtout pas d'article long comme le bras,  quitte à découper en plusieurs partie.

**Comment by kud** [comment]
Oui. :)

**Comment by Uhsac** [comment]
Ok ok, je vais commencer à bosser sur un article d'introduction à docker et plus tard je ferais d'autres articles pour utiliser compose et machine.

**Comment by Uhsac** [comment]
Ok ok je vais bosser sur un plan et je verrais si ça tiens sur un article ou sur plusieurs

**Comment by bloodyowl** [comment]
:+1: @Uhsac fonce

**Comment by Uhsac** [comment]
Il faut obligatoirement io.js pour builder le site ?
Parce que j'ai cette erreur : 
```jsdom 4.x onward only works on io.js, not Node.js™: https://github.com/tmpvar```

**Comment by magsout** [comment]
@Uhsac oui il faut installer io.js

**Comment by Uhsac** [comment]
Sur os x vous conseillez quoi pour utiliser io.js et node en même temps ? nvm ?

**Comment by kud** [comment]
Oui nvm

**Comment by Uhsac** [comment]
Désolé je fais un peu le boulet mais je n'arrive pas à lancé le script.
J'ai cette erreur : 
```
/Users/Clement/Projects/putaindecode/scripts/build.js:174
        throw err;
              ^
TypeError: Cannot read property 'avatar_url' of undefined
    at Avatar.render (/Users/Clement/Projects/putaindecode/src/modules/Avatar/index.jsx:21:29)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/Clement/Projects/putaindecode/node_modules/react/lib/ReactCompositeComponent.js:789:34)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/Users/Clement/Projects/putaindecode/node_modules/react/lib/ReactCompositeComponent.js:816:14)
    at [object Object].wrapper [as _renderValidatedComponent] (/Users/Clement/Projects/putaindecode/node_modules/react/lib/ReactPerf.js:70:21)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/Clement/Projects/putaindecode/node_modules/react/lib/ReactCompositeComponent.js:237:30)
    at [object Object].wrapper [as mountComponent] (/Users/Clement/Projects/putaindecode/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent (/Users/Clement/Projects/putaindecode/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/Clement/Projects/putaindecode/node_modules/react/lib/ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/Users/Clement/Projects/putaindecode/node_modules/react/lib/ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent (/Users/Clement/Projects/putaindecode/node_modules/react/lib/ReactDOMComponent.js:199:12)
    at Object.ReactReconciler.mountComponent (/Users/Clement/Projects/putaindecode/node_modules/react/lib/ReactReconciler.js:38:35)
```

J'ai essayé d'ajouter un fichier à mon nom dans le dossier authors mais ça na pas changé le résultat.

**Comment by MoOx** [comment]
@Uhsac j'ouvre une issue pour ce problème qu'on s'en occupe. En attendant, met le nom d'un autre auteur qui fonctionne :D

**Comment by Uhsac** [comment]
@MoOx Oui c'est ce que j'ai fais ^^

**Comment by Uhsac** [comment]
J'ai fini de bosser sur une première version, vous pouvez la voir [ici](https://github.com/Uhsac/putaindecode.fr/blob/post.introduction-a-docker/content/posts/docker/introduction-a-docker/index.md).

Si vous avez des retours je suis preneurs parce que c'est la première fois que j'écris un article ^^'.

Je vais reprendre quelque partie surtout sur le début, et vérifier l'orthographe car je ne l'ai pas encore fais.

(Et je n'ai pas encore pu me mettre en auteur)

**Comment by MoOx** [comment]
Closing in favor of #439
